### ISSUE TITLE
Update App info layout

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [cdisc-org/cosa#30]
Currently not all of the information is shown. Update they layout and discuss which information to show on the app page.

Show all projectInfo fields
Add a breadcrumb to navigate back to directory
Make some categories clickable (e.g., user clicks on ADaM and get to Directory with ADaM filter selected)?
Hide fields which are blank

**Comment by DmitryMK** [comment]
I have drafted an update in the [appLayout](/cdisc-org/cosa/tree/feature/appLayout) branch. 

* Show all projectInfo fields - there is a button, which allows to show/hide additional details. It is enabled by default in the editor preview and disabled in a standard project view. Not sure we want to show all of the information by default, because some of it feels very specific to an application stage. 
* Hide fields which are blank - done
* Add a breadcrumb to navigate back to directory - replaced a name with breadcrums.
* Make some categories clickable - I did not implement it as it feels a bit complicated. We would have to use context as we are not using redux and I do not think that this feature is so much needed.
